
.PHONY: test clean


test: script.mos
	omc script.mos


clean:
	$(RM) *.c
	$(RM) *.libs
	$(RM) *.log
	$(RM) *.makefile
	$(RM) *_*.c
	$(RM) *_*.h
	$(RM) *_*.o
	$(RM) *_info.json
	$(RM) *_init.xml
	$(RM) ExternalMediaMinimumTest.Test.TestMedium.TestConstants*
